services:
  - type: web
    name: flag-manager-api
    env: node
    region: oregon
    branch: main
    rootDir: .
    plan: starter
    autoDeploy: true
    buildCommand: npm install --include=dev && npm run build:api
    startCommand: npm run start:api
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
